enum ServerErrorTypes {
  ERROR_UNKNOWN = 1,
  ERROR_HTTP_UNAUTHORIZED = 2,
  ERROR_HTTP_BAD_REQUEST = 3,
  ERROR_USERNAME_EXISTS = 4,
  ERROR_LOGIN_INVALID = 5,
  ERROR_PASSWORD_REQUIRED = 6,
  ERROR_EMAIL_REQUIRED = 7,
  ERROR_EMAIL_INVALID = 8,
  ERROR_EMAIL_EXISTS = 9,
  ERROR_INPUT_PARAMETERS_BAD = 10,
  ERROR_NAME_REQUIRED = 11,
  ERROR_DB_WRITE = 12,
  ERROR_DB_READ = 13,
  ERROR_DB_NOT_FOUND = 14,
  ERROR_DB_ALREADY_EXISTS = 15,
}

export default ServerErrorTypes;
